# -*- coding: utf-8 -*-
"""Dia1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opMerRKmcfSi1h2AzQU0OPGmnKYW5Lle
"""



"""# DIA 1

## Temario:
- Tipos de datos
- Operaciones matemáticas
- Operaciones con String
- Operaciones lógicas
- Operaciones Booleanas

## Tipos de Datos
"""

# Existen los datos:
enteros = 2
flotantes = 2.6
# Para saber que tipo de dato es:
type(flotantes)

# Caracteres / Strings
caracteres = "a"
cadena_caracteres = "Hi"

# Booleanos
falso = False # falso es 0
verdadero = True # verdadero es 1

# Imprimir
print(enteros)

"""## El usuario también puede ingresar datos

"""

# Con la función input, el usuario puede ingresar cualquier tipo de dato
# y podemos guardarlo en alguna variable
# (Automaticamente python lo guarda como string)
name = input("Mi nombre es: ")
print(name)

num = input("Ingresa un número: ")
print(num + 1)

num = int(input("Ingresa un número: "))
print(num + 1)

"""## Operaciones matemáticas"""

## 4to Nivel de importancia
# Suma Ordinaria
print("Suma Ordinaria: ")
print (3 + 4)
variable1,variable2 = 20,40
print(variable1 + variable2)

# Resta Ordinaria
print("")
print("Resta Ordinaria: ")
print(2 - 5)
# Declaración de variables
v1 = 10.4
v2 = 15
resultado = v2 - v1
print(resultado)

# 3er Nivel de importancia
# Multiplicación Ordinaria
print("Multiplicación Ordinaria: ")
M1,M2 = 2,3.14
print(M1 * M2)

# División Ordinaria
print("--------------------------------")
print("División Ordinaria: ")
M1,M2,M3,M4,M5,M6 = 2,5,6,5,4,5
print(M1 / M2)
print(M3 / M4)
print(M5 / M6)

#División de Piso
print("--------------------------------")
print("División de Piso")
print(M1 // M2)
print(M3 // M4)
print(M5 // M6)

# Potencia
print("Potencias")
print(2 ** 3)
P1,P2 =7,2
print(P1 ** P2)

print(49 ** (1/2))

# Área de un círculo
pi = 3.14
r = 4
A = pi * (r ** 2)
print(A)

"""##Operación String"""

HM = "Hola Mundo"
print(HM)

a,b = "ta","co"
print(a + b)
print(a + " " + b)

# Animal, debe tener un nombre, le debe gustar una fruta, debe tener una profesión
animal = "Gato"
name = "Kíli"
fruta = "manzana"
profesion = "Ingeniero"
print(f"Hola soy {name} y soy un {animal}, me gusta la {fruta} y soy un {profesion} ")

"""##Operaciones lógicas"""

# Empezamos con los operadores lógicos <,>, <=, >=, and, or (SIEMPRE RETORNA UN BOOLEANO)
b1 = 4 > 5
b2 = 7 > 3
b3 = 14 > 14
b4 = 14 >= 14

# Quieres un sandwich con todo
pan = True
queso = True
mayonesa = True
jamon = False
print(pan and queso and mayonesa and jamon)

print(True * 20)
print(False * 10)